### PR TITLE
updated Fill me

### PR DESCRIPTION
**Pull request by agladstein**

### CODE REVIEW

**Comment by agladstein** [comment]
This might not merge correctly. When I tried to do a rebase it overwrote the notebook. But, we can see...

**Comment by agladstein** [comment]
oh shoot. I accidentally added the sim files. I need to get rid of those...

**Comment by jeromekelleher** [comment]
Would you mind squashing these commits please @agladstein, so that the sim files aren't in the git history?

**Comment by agladstein** [comment]
Shall I merge?

**Comment by jeromekelleher** [comment]
Done!

**Pull request merged**
